/*
 * Hizir Ozcelik | Student Id: 991578495
 * July 4th, 2022 | version 2.2.2  @ Sheridan College
 * PROG20799 | Data Structures and Algorithm Development - C
 * Class#: 1225 | Prof: Muhammad Mohiuddin
 * This program collect and analyze COVID-19 related information based on GTA demographic structure for provincial health ministry.
 * User can insert information up to three household. User cancel manual data entry anytime as well.
 * After manuel data entry is done or cancel intentionally by the user rest of the data generated by the program randomly.
 * Total 100 record is stored. Then with provided options user filter and retrieve information.
 */
#include <stdio.h>
#include "Covid19_Data_Analysis.h"
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <math.h>

// Locations information stored in 2D array
Location locList[][SIZEOFLOCATION] = {
        {"Peel", "Brampton", "Mississauga"},
        {"York", "Maple",    "Vaughan"},
        {"Durham", "Whitby", "Oshawa"}};

// Races list array
Race raceList[SIZEOFRACE] = {"Indigenous", "Caucasian", "African American", "Asian",
                             "Other"};

// Town list array -- for easy implementation it's needed for Main menu option 4
Location townList[SIZEOFTOWNLIST] = {"Brampton", "Mississauga", "Maple", "Vaughan",
                                     "Whitby", "Oshawa"};
// Household data stored in an array
HouseholdData dataArr[SIZEOFDATA];

int main() {
    // Variables and pointers
    int numOfManuelEntry = 1, input = 0, inputRegion = 0, numOfMembers = 0,
            numOfVaccinated = 0, numOfPositive = 0, ctr = 0, isValid = 1, sNo = 0;
    int *entryPtr = &numOfManuelEntry;
    int *isValidPtr = &isValid;
    char buff[SIZEOFDATA];

    puts("-------------------------------------------------------------------------------------------------------------");
    puts("------------------ This program analyzes and stores information related to COVID-19 cases -------------------");
    puts("---------------------------and its impact on various races, regions and towns of GTA-------------------------");
    puts("-------------------------------------------------------------------------------------------------------------");
    puts("--------------------------------------------Manual data entry module-----------------------------------------");

    puts("Provide data of up to three households or enter 9 to skip manual data entry and generate data randomly");

    // Allow user to enter upto three household data. User cancel manuel entry any time to enter 9.
    // Incomplete records are discarded and generated randomly.
    while (numOfManuelEntry <= 3) {
        printf("Data entry for household #%d\n", numOfManuelEntry);

        // Race data gathering
        while (isValid != 0) {
            // Retrieve race names from raceList for data consistency
            printf("Race: enter an integer: %s(0) %s(1) %s(2) %s(3) %s(4) to skip manuel data entry (9)\n",
                   raceList[0].name, raceList[1].name,
                   raceList[2].name, raceList[3].name, raceList[4].name);
            // function call for user input. isValid and numOfManuelEntry variables pass as a pointer to the function
            // so that they can be available for next loops and iterations
            input = getUserInput(isValidPtr, entryPtr, SIZEOFRACE);
            if (input == 9) break; // checking if user input is 9 then cancel the manuel data entry process
            else {
                dataArr[numOfManuelEntry - 1].race = raceList[input]; // Store user input on proper household member.
            }
        }// end of first inner while loop
        if (input == 9) break; // checking if user input is 9 then cancel the manuel data entry process
        isValid = 1; // Resetting the value for next loop

        // Region data gathering
        while (isValid != 0) {
            // Retrieve race names from LocList for data consistency
            printf("Region: enter an integer: %s(0) %s(1) %s(2) to skip manuel data entry (9)\n", locList[0]->name,
                   locList[1]->name, locList[2]->name);
            // function call for user input. isValid and numOfManuelEntry variables pass as a pointer to the function
            // so that they can be available for next loops and iterations
            input = getUserInput(isValidPtr, entryPtr, SIZEOFLOCATION);
            if (input == 9) break; // checking if user input is 9 then cancel the manuel data entry process
            else {
                dataArr[numOfManuelEntry - 1].region = *locList[input];
                inputRegion = input; // region selection stored in a variable because it is needed for town data gathering
            }
        }// end of second inner while loop
        if (input == 9) break; // checking if user input is 9 then cancel the manuel data entry process
        isValid = 1;// Resetting the value for next loop

        //Town data gathering
        while (isValid != 0) {
            // Retrieve race names from LocList for data consistency
            printf("Town: enter an integer: %s(0) %s(1) to skip manuel data entry (9)\n", locList[inputRegion][1].name,
                   locList[inputRegion][2].name);
            // function call for user input. isValid and numOfManuelEntry variables pass as a pointer to the function
            // so that they can be available for next loops and iterations
            input = getUserInput(isValidPtr, entryPtr, SIZEOFTOWN);
            if (input == 9) break; // checking if user input is 9 then cancel the manuel data entry process
            else dataArr[numOfManuelEntry - 1].town = locList[inputRegion][input + 1];
        }
        if (input == 9) break; // checking if user input is 9 then cancel the manuel data entry process
        isValid = 1;// Resetting the value for next loop

        //income data gathering
        printf("Enter annual household income. Enter (9) to skip manuel data entry\n");
        printf("It will be rounded to the nearest hundred.\n");
        while (isValid != 0) {
            input = getUserInput(isValidPtr, entryPtr, 150000);
            if (input == 9) break;// checking if user input is 9 then cancel the manuel data entry process
            else
                dataArr[numOfManuelEntry - 1].income =
                        floor(input / 100) * 100;// rounding down income to the nearest hundreds
        }
        if (input == 9) break;// checking if user input is 9 then cancel the manuel data entry process
        isValid = 1; // Resetting the value for next loop

        // Households data gathering
        printf("Enter number of household members, members fully vaccinated for COVID-19 and members tested positive"
               "COVID-19 respectively as three integers seperated by space or tab\n");
        while (isValid != 0) {
            fgets(buff, sizeof(buff), stdin);
            ctr = sscanf(buff, "%d%d%d", &numOfMembers, &numOfVaccinated, &numOfPositive);
            if (ctr != 3 || numOfMembers < 0 || numOfVaccinated < 0 || numOfPositive < 0) {
                printf("Please enter three positive number seperated by space or tab\n");
            } else if (numOfVaccinated > numOfMembers || numOfPositive > numOfMembers) {
                puts("Number of vaccinated members or Covid-19 positive members cannot be greater than the total member of the house");
            } else {
                sNo++;
                dataArr[numOfManuelEntry - 1].id = sNo;
                dataArr[numOfManuelEntry - 1].totalNumberOfHousehold = numOfMembers;
                dataArr[numOfManuelEntry - 1].fullyVaccinated = numOfVaccinated;
                dataArr[numOfManuelEntry - 1].testedPositive = numOfPositive;
                isValid = 0;
            }
        }//end of household' members data gathering
        isValid = 1; // Resetting the value for next loop
        // checking if three record stored successfully
        if (numOfManuelEntry == 3) {
            break;
        } else numOfManuelEntry++;
    } // end of outer while loop  -- end of manuel entry module

    // Generating data randomly
    srand(time(NULL));
    for (int dex = numOfManuelEntry; dex < SIZEOFDATA; dex++) {
        sNo++;
        dataArr[dex].id = sNo;
        dataArr[dex].race = raceList[rand() % SIZEOFRACE];
        int dexRegion = rand() % SIZEOFLOCATION;
        dataArr[dex].region = *locList[dexRegion];
        dataArr[dex].town = locList[dexRegion][rand() % SIZEOFTOWN + 1];
        int num = (rand() % (90000 + 1) + 10000);// income range is 10K to 100K
        int rounded = floor(num / 100) * 100;
        dataArr[dex].income = rounded;
        int sizeOfFamily = rand() % 10 + 1; // min 1, max 10 people
        dataArr[dex].totalNumberOfHousehold = sizeOfFamily;
        dataArr[dex].fullyVaccinated = rand() % sizeOfFamily + 1;// limit with respective size of family
        dataArr[dex].testedPositive = rand() % sizeOfFamily + 1;// limit with respective size of family
    }
    printf("Content to file written successfully!\n");
    delay(800);// delay
    //Displaying data fully populated dataset
    printDataSet(dataArr);
    // Main Menu displaying options
    input = 1;// Resetting the value for next loop
    while (input != 0) {
        puts("Main Menu : ");
        puts("Enter your choice to display");
        puts("1. Household records by race, region or town");
        puts("2. Races ranking for COVID-19");
        puts("3. Regions ranking for COVID-19");
        puts("4. Towns ranking for COVID-19");
        puts("5. Races ranking fo poverty");
        puts("0. Exit");

        fgets(buff, sizeof(buff), stdin);
        sscanf(buff, "%d", &input);
        switch (input) {
            case 1:
                puts("Enter an integer to see household records of a particular race(0) region(1) town(2)");
                int input1;
                fgets(buff, sizeof(buff), stdin);
                sscanf(buff, "%d", &input1);
                // Household records by race, region, town
                switch (input1) {
                    case 0:
                        printf("Race: enter an integer: %s(0) %s(1) %s(2) %s(3) %s(4)\n", raceList[0].name,
                               raceList[1].name, raceList[2].name, raceList[3].name, raceList[4].name);
                        int inputRace;
                        fgets(buff, sizeof(buff), stdin);
                        ctr = sscanf(buff, "%d", &inputRace);
                        if (ctr != 1 || inputRace >= SIZEOFRACE) {
                            printf("Invalid entry!!! Returning main menu...\n");
                        } else {
                            printf("%4s%20s%10s%15s%12s%15s%15s%20s\n", "S.no", "Race", "Region", "Town", "Income",
                                   "Family Size", "Vaccinated", "Covid-19 Positive");
                            sNo = 0;
                            for (int dex = 0; dex < SIZEOFDATA; dex++) {
                                if (strcmp(dataArr[dex].race.name, raceList[inputRace].name) == 0) {
                                    sNo++;
                                    printf("%4d%20s%10s%15s%12d%15d%15d%20d\n", sNo, dataArr[dex].race.name,
                                           dataArr[dex].region.name, dataArr[dex].town.name,
                                           dataArr[dex].income, dataArr[dex].totalNumberOfHousehold,
                                           dataArr[dex].fullyVaccinated, dataArr[dex].testedPositive);
                                }
                            }
                            printf("\n********************************************* %d records are found ************************************************\n",
                                   sNo);
                        }
                        break;
                    case 1:
                        printf("Region: enter an integer: %s(0) %s(1) %s(2)\n", locList[0]->name, locList[1]->name,
                               locList[2]->name);
                        inputRegion = 0;
                        fgets(buff, sizeof(buff), stdin);
                        ctr = sscanf(buff, "%d", &inputRegion);
                        if (ctr != 1 || inputRegion >= SIZEOFLOCATION) {
                            printf("Invalid entry!!! Returning main menu...\n");
                        } else {
                            printf("%4s%20s%10s%15s%12s%15s%15s%20s\n", "S.no", "Race", "Region", "Town", "Income",
                                   "Family Size", "Vaccinated", "Covid-19 Positive");
                            sNo = 0;
                            for (int dex = 0; dex < SIZEOFDATA; dex++) {
                                if (strcmp(dataArr[dex].region.name, locList[inputRegion]->name) == 0) {
                                    sNo++;
                                    printf("%4d%20s%10s%15s%12d%15d%15d%20d\n", sNo, dataArr[dex].race.name,
                                           dataArr[dex].region.name,
                                           dataArr[dex].town.name, dataArr[dex].income,
                                           dataArr[dex].totalNumberOfHousehold,
                                           dataArr[dex].fullyVaccinated, dataArr[dex].testedPositive);
                                }
                            }
                            printf("\n********************************************* %d records are found ************************************************\n",
                                   sNo);
                        }
                        break;
                    case 2:
                        printf("Town: enter an integer: %s(0) %s(1) %s(2) %s(3) %s(4) %s(5)\n", townList[0].name,
                               townList[1].name, townList[2].name, townList[3].name, townList[4].name,
                               townList[5].name);
                        int inputTown;
                        fgets(buff, sizeof(buff), stdin);
                        ctr = sscanf(buff, "%d", &inputTown);
                        if (ctr != 1 || inputTown >= SIZEOFTOWNLIST) {
                            printf("Invalid entry!!! Returning main menu...\n");
                        } else {
                            printf("%4s%20s%10s%15s%12s%15s%15s%20s\n", "S.no", "Race", "Region", "Town", "Income",
                                   "Family Size", "Vaccinated", "Covid-19 Positive");
                            sNo = 0;
                            for (int dex = 0; dex < SIZEOFDATA; dex++) {
                                if (strcmp(dataArr[dex].town.name, townList[inputTown].name) == 0) {
                                    sNo++;
                                    printf("%4d%20s%10s%15s%12d%15d%15d%20d\n", sNo, dataArr[dex].race.name,
                                           dataArr[dex].region.name, dataArr[dex].town.name, dataArr[dex].income,
                                           dataArr[dex].totalNumberOfHousehold, dataArr[dex].fullyVaccinated,
                                           dataArr[dex].testedPositive);
                                }
                            }
                            printf("\n********************************************* %d records are found ************************************************\n",
                                   sNo);
                        }
                        break;
                    default :
                        printf("Invalid entry!!! Returning main menu...\n");
                }
                break;
                // Races ranking of COVID-19
            case 2:
                puts("Enter 0 to see all COVID-19 cases tested or\n1 for only tested positive cases or\n9 to go back to main menu");
                int input2;
                fgets(buff, sizeof(buff), stdin);
                sscanf(buff, "%d", &input2);
                switch (input2) {
                    case 0:
                        puts("------------ Races ranking of COVID-19 -----------");
                        printf("%20s : %20s\n", "Races", "Covid-19 Positive");

                        // counting totalNumOfFamily case positive by races
                        int i = 0;
                        while (i < SIZEOFRACE) {
                            int totalPositiveCases = 0;
                            for (int dex = 0; dex < SIZEOFDATA; dex++) {
                                if (strcmp(dataArr[dex].race.name, raceList[i].name) == 0) {
                                    totalPositiveCases = totalPositiveCases + dataArr[dex].testedPositive;
                                }
                            }
                            printf("%20s : %20d\n", raceList[i].name, totalPositiveCases);
                            i++;
                        }
                        break;
                    case 1:
                        puts("------------ Races ranking of COVID-19 -----------");
                        printf("%20s : %20s\n", "Races", "Fully Vaccinated");
                        // counting totalNumOfFamily fully vaccinated by races
                        i = 0;
                        while (i < SIZEOFRACE) {
                            int totalCases = 0;
                            for (int dex = 0; dex < SIZEOFDATA; dex++) {
                                if (strcmp(dataArr[dex].race.name, raceList[i].name) == 0) {
                                    totalCases = totalCases + dataArr[dex].fullyVaccinated;
                                }
                            }
                            printf("%20s : %20d\n", raceList[i].name, totalCases);
                            i++;
                        }
                        break;
                    case 9:
                        break;
                    default :
                        printf("Invalid entry!!! Returning main menu...\n");
                }
                break;
                // Regions ranking of COVID-19
            case 3:
                puts("Enter 0 to see all COVID-19 cases tested or\n1 for only tested positive cases or\n9 to go back to main menu");
                int input3 = 0;
                fgets(buff, sizeof(buff), stdin);
                sscanf(buff, "%d", &input3);
                switch (input3) {
                    case 0:
                        puts("------------ Regions ranking of COVID-19 -----------");
                        printf("%20s : %20s\n", "Regions", "Covid-19 Positive");

                        // counting totalNumOfFamily case positive by regions
                        int i = 0;
                        while (i < SIZEOFLOCATION) {
                            int totalPositiveCases = 0;
                            for (int dex = 0; dex < SIZEOFDATA; dex++) {
                                if (strcmp(dataArr[dex].region.name, locList[i][0].name) == 0) {
                                    totalPositiveCases = totalPositiveCases + dataArr[dex].testedPositive;
                                }
                            }
                            printf("%20s : %20d\n", locList[i][0].name, totalPositiveCases);
                            i++;
                        }
                        break;
                    case 1:
                        puts("------------ Regions ranking of COVID-19 -----------");
                        printf("%20s : %20s\n", "Regions", "Fully Vaccinated");
                        // counting totalNumOfFamily fully vaccinated by regions
                        i = 0;
                        while (i < SIZEOFLOCATION) {
                            int totalCases = 0;
                            for (int dex = 0; dex < SIZEOFDATA; dex++) {
                                if (strcmp(dataArr[dex].region.name, locList[i][0].name) == 0) {
                                    totalCases = totalCases + dataArr[dex].fullyVaccinated;
                                }
                            }
                            printf("%20s : %20d\n", locList[i][0].name, totalCases);
                            i++;
                        }
                        break;
                    case 9:
                        break;
                    default :
                        printf("Invalid entry!!! Returning main menu...\n");
                }
                break;

                // Towns ranking of COVID-19
            case 4:
                puts("Enter 0 to see all COVID-19 cases tested or\n1 for only tested positive cases or\n9 to go back to main menu");
                int input4 = 0;
                fgets(buff, sizeof(buff), stdin);
                sscanf(buff, "%d", &input4);
                switch (input4) {
                    case 0:
                        puts("------------ Towns ranking of COVID-19 -----------");
                        printf("%20s : %20s\n", "Towns", "Covid-19 Positive");
                        // counting totalNumOfFamily case positive by town
                        int i = 0;
                        while (i < SIZEOFTOWNLIST) {
                            int totalPositiveCases = 0;
                            for (int dex = 0; dex < SIZEOFDATA; dex++) {
                                if (strcmp(dataArr[dex].town.name, townList[i].name) == 0) {
                                    totalPositiveCases = totalPositiveCases + dataArr[dex].testedPositive;
                                }
                            }
                            printf("%20s : %20d\n", townList[i].name, totalPositiveCases);
                            i++;
                        }
                        break;
                    case 1:
                        puts("------------ Regions ranking of COVID-19 -----------");
                        printf("%20s : %20s\n", "Regions", "Fully Vaccinated");
                        // counting totalNumOfFamily fully vaccinated by town
                        i = 0;
                        while (i < SIZEOFTOWNLIST) {
                            int totalCases = 0;
                            for (int dex = 0; dex < SIZEOFDATA; dex++) {
                                if (strcmp(dataArr[dex].town.name, townList[i].name) == 0) {
                                    totalCases = totalCases + dataArr[dex].fullyVaccinated;
                                }
                            }
                            printf("%20s : %20d\n", townList[i].name, totalCases);
                            i++;
                        }
                        break;
                    case 9:
                        break;
                    default :
                        printf("Invalid entry!!! Returning main menu...\n");
                }
                break;
                // Races ranking by poverty
            case 5:
                puts("----------------------- Races ranking by poverty ---------------------");
                printf("%20s : %20s%25s\n", "Races", "Average income", "Percentage of poverty");
                int totalNumOfFamily; // totalNumOfFamily number of record for specific race
                int incomeTotal, i;
                for (i = 0; i < SIZEOFRACE; i++) {
                    ctr = 0;//totalNumOfFamily number of family in poverty
                    totalNumOfFamily = 0;
                    incomeTotal = 0;
                    for (int dex = 0; dex < SIZEOFDATA; dex++) {
                        if (strcmp(dataArr[dex].race.name, raceList[i].name) == 0) {
                            totalNumOfFamily++;
                            incomeTotal = incomeTotal + dataArr[dex].income;
                            if ((dataArr[dex].totalNumberOfHousehold == 1 && dataArr[dex].income < 30000) ||
                                (dataArr[dex].totalNumberOfHousehold == 2 && dataArr[dex].income < 35000) ||
                                (dataArr[dex].totalNumberOfHousehold == 3 && dataArr[dex].income < 40000) ||
                                (dataArr[dex].totalNumberOfHousehold == 4 && dataArr[dex].income < 45000) ||
                                (dataArr[dex].totalNumberOfHousehold >= 5 && dataArr[dex].income < 50000)) {
                                ctr++;
                            }
                        }
                    }
                    // Average income for a race
                    int avgIncome = incomeTotal / totalNumOfFamily;
                    int roundedAvgIncome = floor(avgIncome / 100) * 100;
                    // totalNumOfFamily number of poor family on a particular race / totalNumOfFamily number of record on a particular race * 100
                    int percentage = ctr * 100 / totalNumOfFamily;
                    printf("%20s : %20d%25d\n", raceList[i].name, roundedAvgIncome, percentage);
                }
                break;
            case 0:
                printf("%s", "Exiting the program.... Thank you!\n");
                printf("%s", "(c)Hizir Ozcelik @Sheridan College July, 2022");
                break;
            default :
                printf("Invalid entry!!! Returning main menu...\n");
        }
    } // End of while the most outer loop
    return 0;
} // End of Main()